### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'CONTAINERS'

### ISSUE THREAD

**Issue by qcoumes** [plgitlogin/sandbox#14]
This errors sometime occurs randomly:

```
An unknown error occured:
Traceback (most recent call last):
File "/srv/local/pl/pl-sandbox/sandbox/views.py", line 112, in post
container = ContainerWrapper.acquire()
File "/srv/local/pl/pl-sandbox/sandbox/container.py", line 71, in acquire
cw = next((c for c in settings.CONTAINERS if c.available), None)
File "/usr/local/lib/python3.5/dist-packages/django/conf/init.py", line 58, in getattr
val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'CONTAINERS'
```

**Comment by nimdanor** [comment]
This is why we shloud have a group of sandbox with different implementation.
