### ISSUE TITLE
Exception when launching  sandbox

### ISSUE THREAD

**Issue by Pavell94000** [plgitlogin/sandbox#18]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.35/containers/create?name=c2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pavell/Alternance/sandbox/sandbox/container.py", line 178, in initialise_container
    CONTAINERS.append(ContainerWrapper("c%d" % i, i))
  File "/home/pavell/Alternance/sandbox/sandbox/container.py", line 46, in __init__
    self.container = create_container(name)
  File "/home/pavell/Alternance/sandbox/sandbox/container.py", line 33, in create_container
    "mode": "rw",
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/models/containers.py", line 785, in run
    detach=detach, **kwargs)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/pavell/Alternance/env_s/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/c2" is already in use by container "b5eed4b89f72818688d7a99c82cfdd3850ab029deb3e9db554f994f1ed5eb4bd". You have to remove (or rename) that container to be able to reuse that name.")

The sandbox seems to work correctly though.

**Comment by qcoumes** [comment]
Solved on 1.0.0
